name: Test and Build Backend

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: b2b_v2_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run linter
      run: pnpm run lint 2>/dev/null || true

    - name: Run tests
      run: pnpm test
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/b2b_v2_test

    - name: Build project
      run: pnpm build

    - name: Build Docker image
      run: docker build -t b2b_v2_backend:${{ github.sha }} .

    - name: Upload Docker image
      if: github.ref == 'refs/heads/master'
      run: |
        echo "Docker image ready for deployment: b2b_v2_backend:${{ github.sha }}"
